EmlSoft.KBSTest.WebApp/Controllers/GraberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EmlSoft.KBSTest.WebApp.Controllers
{
    public class GraberController : Controller
    {
        readonly Domain.ISourceRepository m_Rep;
        readonly Domain.IGrubber m_Gruber;

        public GraberController(Domain.ISourceRepository Rep, Domain.IGrubber Gruber)
        {
			m_Rep = Rep ?? throw new ArgumentNullException(nameof(Rep));

            m_Gruber = Gruber ?? throw new ArgumentNullException(nameof(Gruber));
        }

        // GET: Graber
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> GetList()
        {
            if (Request.IsAjaxRequest())
            {
                var ret = (await m_Rep.GetListAsync(0, 0)).Select(p => p.Id).ToArray();
                return Json(ret);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DoGrub(int Id)
        {
            if (Request.IsAjaxRequest())
            {
                var Src = m_Rep.GetItemById(Id);
                try
                {
                    string Context = m_Gruber.Grub(Src.Url);

                    m_Rep.SaveSourceContext(Id, Context);

                    return Json(new { Status = 1, Name = Src.Url, Comment = string.Empty });
                }
                catch (Exception ex)
                {
                    return Json(new { Status = 0, Name = Src.Url, Comment = ex.Message });
                }
            }
            return RedirectToAction("Index");
        }

    }
}

EmlSoft.KBSTest.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmlSoft.KBSTest.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EmlSoft.KBSTest.WebApp/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EmlSoft.KBSTest.WebApp.Controllers
{
    public class SearchController : Controller
    {
        readonly Domain.ISourceRepository m_Rep;

        public SearchController(Domain.ISourceRepository Rep )
        {
			m_Rep = Rep ?? throw new ArgumentNullException( nameof(Rep));
        }

        // GET: Search
        public async Task<ActionResult> Index(string SearchStr)
        {
            var ret = await m_Rep.SerachAsync(SearchStr);

            return View(ret);
        }
    }
}

EmlSoft.KBSTest.WebApp/Controllers/SourceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace EmlSoft.KBSTest.WebApp.Controllers
{
    public class SourceController : Controller
    {
        ModelView.ISourceModelView m_ModelView;

        public SourceController(ModelView.ISourceModelView ModelView )
        {
            m_ModelView = ModelView ?? throw new ArgumentNullException( nameof(ModelView));
		}

        // GET: Source
        public async Task<ActionResult> Index(int Id = 0, int Direction = 1)
        {
            IEnumerable<Domain.Source> ret = await m_ModelView.GetIndexAsync(Id, Direction);

            return View(ret);
        }

        // GET: Source/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Source/Create
        [HttpPost]
        public async Task<ActionResult> Create(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await m_ModelView.CreateAsync(collection["Url"]);

                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }

            return View(new Domain.Source { Url = collection["Url"] } );
        }

        // GET: Source/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var Src = await m_ModelView.GetItemByIdAsync(id);

            return View( Src );
        }

        // POST: Source/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int ? id , FormCollection collection)
        {
            if( id == null )
                return RedirectToAction("Index");
            try
            {
                if (ModelState.IsValid)
                {
                    await m_ModelView.UpdateAsync(new Domain.Source { Id = id ?? 0, Url = collection["Url"] });

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(new Domain.Source { Url = collection["Url"] });
        }

        // GET: Source/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var Src = await m_ModelView.GetItemByIdAsync(id);

            return View(Src);
        }

        // POST: Source/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int ? id, FormCollection collection)
        {
            if( id == null  )
                return RedirectToAction("Index");

            try
            {
                if (ModelState.IsValid)
                {
                    await m_ModelView.DeleteAsync(id ?? 0);

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message );
            }

            return View(new Domain.Source { Url = collection["Url"] });
        }
    }
}

EmlSoft.KBSTest.WebApp/Views/Graber/Index.cshtml
@model IEnumerable<EmlSoft.KBSTest.Domain.Source>

<script src="~/Scripts/grabber.js"></script>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table Id="ListTable" class="table">
    <tr>
        <th>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
    </tr>
</table>

<input id="GrubButton" type="button" value="Загрузка" onclick="doRequest()" />

EmlSoft.KBSTest.WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EmlSoft.KBSTest.WebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EmlSoft.KBSTest.WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Новый поисковик";
}

<div class="jumbotron">
    <h1>Yandex NEW!!!!</h1>
</div>

EmlSoft.KBSTest.WebApp/Views/Search/Index.cshtml
@model IEnumerable<EmlSoft.KBSTest.Domain.SearchResult>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm())
{
    <p>
        Search Name: @Html.TextBox("SearchStr", ViewBag.FilterValue as string)
        <input type="submit" value="Find" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Result)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Result)
        </td>
    </tr>
}

</table>

EmlSoft.KBSTest.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Яндекс КБС", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" title="Три источника, три составные части">
                    <li>@Html.ActionLink("Источники", "Index", "Source")</li>
                    <li>@Html.ActionLink("Сбор данных", "Index", "Graber")</li>
                    <li>@Html.ActionLink("Поиск", "Index", "Search")</li>
                </ul>
                <ul class="nav navbar-nav" >
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EmlSoft.KBSTest.WebApp/Views/Source/Create.cshtml
@model EmlSoft.KBSTest.Domain.Source

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Source</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmlSoft.KBSTest.WebApp/Views/Source/Delete.cshtml
@model EmlSoft.KBSTest.Domain.Source

@{
    ViewBag.Title = "Delete";
}

<h2>Удаление</h2>

<h3>Вы уверены, что ребуется удалить запись?</h3>
<div>
    <h4>Источник</h4>
    <hr>@Html.ValidationMessage(string.Empty, new { @class = "text-danger" })</hr>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EmlSoft.KBSTest.WebApp/Views/Source/Edit.cshtml
@model EmlSoft.KBSTest.Domain.Source

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Source</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmlSoft.KBSTest.WebApp/Views/Source/Index.cshtml
@model IEnumerable<EmlSoft.KBSTest.Domain.Source>

@{
    ViewBag.Title = "Список источников";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Добавить новый источник", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

@Html.ActionLink("<<", "Index" , new { Id = 0, Direction = 1 } ) |
@Html.ActionLink("<", "Index", new { Id = Model?.FirstOrDefault()?.Id  ?? 0, Direction = -1 }) |
@Html.ActionLink(">", "Index", new { Id = Model?.LastOrDefault()?.Id ?? int.MaxValue, Direction = 1 }) |
@Html.ActionLink(">>", "Index", new { Id = int.MaxValue, Direction = -1 }) 